name = "turbo-workers-cache"
main = "src/index.ts"
compatibility_date = "2024-02-26"
node_compat = true
minify = true

[placement]
mode = "smart"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'turbo-workers-cache'
